// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrjgTbeZBg2S1_sH4FlSIUvuTppx8D4EQ',
    appId: '1:344624073313:web:a26d2b9d95cdeeb68bb820',
    messagingSenderId: '344624073313',
    projectId: 'flutter-sandbox-1b35d',
    authDomain: 'flutter-sandbox-1b35d.firebaseapp.com',
    storageBucket: 'flutter-sandbox-1b35d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkZyu0Y5tSdwraHQgOfLdtS0XdBF3MTM0',
    appId: '1:344624073313:android:62175a390daf10498bb820',
    messagingSenderId: '344624073313',
    projectId: 'flutter-sandbox-1b35d',
    storageBucket: 'flutter-sandbox-1b35d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvbOCN7pXpagr47ZHdAFGnpWUODMRA21I',
    appId: '1:344624073313:ios:0d9bb28a4155f2798bb820',
    messagingSenderId: '344624073313',
    projectId: 'flutter-sandbox-1b35d',
    storageBucket: 'flutter-sandbox-1b35d.appspot.com',
    iosClientId: '344624073313-svarur1ka06kbe9v6jbjqfei30hqbbmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSandbox',
  );
}
